############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Blog"
url = "/blog"
weight = 2

[[main]]
name = "Research"
url = "/publications"
weight = 3

[[main]]
name = "Talks"
url = "/talks"
weight = 4

[[main]]
name = "Advisories"
url = "/advisories"
weight = 5

[[main]]
name = "About"
url = "/about"
weight = 6

[[main]]
name = "Contact"
url = "/contact"
weight = 7

# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Privacy Policy"
url = "/privacy"
weight = 2
